# Generated by Django 5.0.1 on 2024-01-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobDetailsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_discription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_exp_years',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
